"""initial schema

Revision ID: 1745c744261d
Revises: 
Create Date: 2026-02-09 18:49:12.391107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1745c744261d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversion_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('click_id', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('revenue_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_events_click_id'), 'conversion_events', ['click_id'], unique=False)
    op.create_index('ix_conversion_events_org_type', 'conversion_events', ['organization_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_conversion_events_organization_id'), 'conversion_events', ['organization_id'], unique=False)
    op.create_table('creators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('handle', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('platform_user_id', sa.String(length=255), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creators_handle'), 'creators', ['handle'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('billing_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('pageview_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('click_id', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('page_url', sa.Text(), nullable=True),
    sa.Column('time_on_page_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pageview_events_click_id'), 'pageview_events', ['click_id'], unique=False)
    op.create_index(op.f('ix_pageview_events_organization_id'), 'pageview_events', ['organization_id'], unique=False)
    op.create_table('refund_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('click_id', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('original_order_id', sa.String(length=255), nullable=True),
    sa.Column('refund_amount_cents', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refund_events_click_id'), 'refund_events', ['click_id'], unique=False)
    op.create_index(op.f('ix_refund_events_organization_id'), 'refund_events', ['organization_id'], unique=False)
    op.create_table('session_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('click_id', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('page_url', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_events_click_id'), 'session_events', ['click_id'], unique=False)
    op.create_index(op.f('ix_session_events_organization_id'), 'session_events', ['organization_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_slug'), 'campaigns', ['slug'], unique=False)
    op.create_table('links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('creator_handle', sa.String(length=100), nullable=False),
    sa.Column('campaign_slug', sa.String(length=100), nullable=False),
    sa.Column('asset_slug', sa.String(length=100), nullable=True),
    sa.Column('destination_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_links_route_lookup', 'links', ['creator_handle', 'campaign_slug', 'asset_slug'], unique=True)
    op.create_table('click_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('click_id', sa.String(length=100), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referer', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('device_class', sa.String(length=20), nullable=True),
    sa.Column('os_family', sa.String(length=50), nullable=True),
    sa.Column('browser_family', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('bot_blocked', sa.Boolean(), nullable=True),
    sa.Column('bot_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('destination_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_events_click_id'), 'click_events', ['click_id'], unique=True)
    op.create_index('ix_click_events_creator_created', 'click_events', ['creator_id', 'created_at'], unique=False)
    op.create_index('ix_click_events_org_created', 'click_events', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_click_events_organization_id'), 'click_events', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_click_events_organization_id'), table_name='click_events')
    op.drop_index('ix_click_events_org_created', table_name='click_events')
    op.drop_index('ix_click_events_creator_created', table_name='click_events')
    op.drop_index(op.f('ix_click_events_click_id'), table_name='click_events')
    op.drop_table('click_events')
    op.drop_index('ix_links_route_lookup', table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_campaigns_slug'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_session_events_organization_id'), table_name='session_events')
    op.drop_index(op.f('ix_session_events_click_id'), table_name='session_events')
    op.drop_table('session_events')
    op.drop_index(op.f('ix_refund_events_organization_id'), table_name='refund_events')
    op.drop_index(op.f('ix_refund_events_click_id'), table_name='refund_events')
    op.drop_table('refund_events')
    op.drop_index(op.f('ix_pageview_events_organization_id'), table_name='pageview_events')
    op.drop_index(op.f('ix_pageview_events_click_id'), table_name='pageview_events')
    op.drop_table('pageview_events')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_creators_handle'), table_name='creators')
    op.drop_table('creators')
    op.drop_index(op.f('ix_conversion_events_organization_id'), table_name='conversion_events')
    op.drop_index('ix_conversion_events_org_type', table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_click_id'), table_name='conversion_events')
    op.drop_table('conversion_events')
    # ### end Alembic commands ###
